### ISSUE TITLE
twitter_handle for nil:NilClass

### ISSUE THREAD

**Issue by fousa** [MSch/devise-twitter#8]
When coming back from Twitter I always get this error:

undefined method `twitter_handle=' for nil:NilClass

Any idea why?

**Comment by MSch** [comment]
Can you provide the backtrace?

**Comment by fousa** [comment]
Here you go!

activesupport (3.0.0) lib/active_support/whiny_nil.rb:48:in `method_missing'
/Users/jelle/Sites/Forks/devise-twitter/lib/devise/twitter/warden.rb:14:in`block in <top (required)>'
warden_oauth (0.1.1) lib/warden_oauth/strategy.rb:101:in `find_user_by_access_token'
warden_oauth (0.1.1) lib/warden_oauth/strategy.rb:55:in`authenticate!'
/Users/jelle/Sites/Forks/devise-twitter/lib/devise/twitter/rack.rb:16:in `block in <module:Rack>'
/Users/jelle/Sites/Forks/devise-twitter/lib/devise/twitter/rack.rb:45:in`call'
/Users/jelle/Sites/Forks/devise-twitter/lib/devise/twitter/rack.rb:45:in `block in <module:Rack>'
actionpack (3.0.0) lib/action_dispatch/routing/mapper.rb:34:in`call'
actionpack (3.0.0) lib/action_dispatch/routing/mapper.rb:34:in `call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in`block in call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in `block in recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:68:in`optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in `recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in`call'
actionpack (3.0.0) lib/action_dispatch/routing/route_set.rb:492:in `call'
haml (3.0.18) lib/sass/plugin/rack.rb:41:in`call'
warden (0.10.7) lib/warden/manager.rb:35:in `block in call'
warden (0.10.7) lib/warden/manager.rb:34:in`catch'
warden (0.10.7) lib/warden/manager.rb:34:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
actionpack (3.0.0) lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in`call'
actionpack (3.0.0) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/flash.rb:182:in`call'
actionpack (3.0.0) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/cookies.rb:287:in`call'
activerecord (3.0.0) lib/active_record/query_cache.rb:32:in `block in call'
activerecord (3.0.0) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
activerecord (3.0.0) lib/active_record/query_cache.rb:12:in `cache'
activerecord (3.0.0) lib/active_record/query_cache.rb:31:in`call'
activerecord (3.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/callbacks.rb:46:in`block in call'
activesupport (3.0.0) lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
actionpack (3.0.0) lib/action_dispatch/middleware/callbacks.rb:44:in`call'
rack (1.2.1) lib/rack/sendfile.rb:107:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
actionpack (3.0.0) lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
railties (3.0.0) lib/rails/rack/logger.rb:13:in`call'
rack (1.2.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.0.0) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.2.1) lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in`synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
actionpack (3.0.0) lib/action_dispatch/middleware/static.rb:30:in`call'
railties (3.0.0) lib/rails/application.rb:168:in `call'
railties (3.0.0) lib/rails/application.rb:77:in`method_missing'
railties (3.0.0) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in`call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/Users/jelle/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
/Users/jelle/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/Users/jelle/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

**Comment by MSch** [comment]
Looks like you are using the connect url when you should be using the signup url?

**Comment by htapal** [comment]
I bet this is due to this issue I just created https://github.com/MSch/devise-twitter/issues/#issue/18
